### ISSUE TITLE
Niezrenderowany templejt.

### ISSUE THREAD

**Issue by whoamipl** [not7cd/black-sheep#1]
Zauważyłem, że w pewnym miejscu na stronie nie renderuje się template i widnieje tam takie coś:
```
{% for event in site.posts %}

{{ event.title }} [{{ event.date | date: “%Y” }}]
{% endfor %}
```
Problem występuję w punkcie wydarzenia.

**Comment by not7cd** [comment]
To  pewnie jeszcze zaszłości z Jekylla, będzie to przepisane na Hugo
